<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>ADS08 Dummy Rule</name>
  <uuid>1c471c85-331c-4277-907a-9300816c0cee</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if false then set decision to null ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
