<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Dummy Rule</name>
  <uuid>db0dfd70-1b40-413e-b53a-bc270f4dcc89</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if false then set decision to null ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
