<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Dummy  From Other User</name>
  <uuid>f149847c-10dc-4ec5-bc37-1f2ce0c1b124</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if false then set decision to null ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
